name = "workers"
main = "worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = [ "nodejs_compat", "nodejs_als" ]

[assets]
binding = "ASSETS"
directory = "./build"
#run_worker_first = true
#not_found_handling = "single-page-application"

#[[d1_databases]]
binding = "MEDIADB"
database_name = "tg"
database_id = "619bf710-136f-4b05-b7a7-ce7ffef02990"

[placement]
mode = "smart"

#[limits]
#cpu_ms = 300000

#[vars]
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
